version: '2.9'

services:

  procore-intacct-localstack:
    image: localstack/localstack
    container_name: procore-intacct-localstack
    hostname: procore-intacct-localstack
    healthcheck:
      test: awslocal cloudformation list-stacks
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - SERVICES=sam,cloudformation,apigateway,lambda,sns,sqs
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=local
      - LOCALSTACK_HOSTNAME=0.0.0.0
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - procore-intacct-localstack-volume:/tmp/localstack
      - ~/.aws:/root/.aws
    ports:
      - '2001:4566'

volumes:

  procore-intacct-localstack-volume:
    driver: local
