version: '3.3'
services:
  localstack:
    build:
      context: .
    image: localstack
    container_name: localstack
    hostname: localstack
    healthcheck:
      test: cd /devops && make healthcheck e=local
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=0.0.0.0
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_PROFILE=${AWS_PROFILE}
      - DEFAULT_REGION=${AWS_REGION}
      - DEFAULT_STACK=${AWS_STACK}
      - SERVICES=cloudformation,lambda,sam,apigateway
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=local
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - ~/.aws:/root/.aws
      - ./:/devops
    ports:
      - 2000:8080
      - 2001:4566
