version: '2.9'

services:

  procore-intacct-localstack:
    image: localstack/localstack
    container_name: procore-intacct-localstack
    hostname: procore-intacct-localstack
    healthcheck:
      test: awslocal cloudformation list-stacks
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    environment:
      - SERVICES=sam,cloudformation,apigateway,lambda,sns,sqs
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_EXECUTOR=local
      - LOCALSTACK_HOSTNAME=0.0.0.0
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - procore-intacct-localstack-volume:/tmp/localstack
      - ~/.aws:/root/.aws
    ports:
      - '2001:4566'

  procore-intacct-gateway-lambda:
    build:
      context: ./src/lambda/gateway
    image: procore-intacct-gateway-lambda
    container_name: procore-intacct-gateway-lambda
    hostname: procore-intacct-gateway-lambda
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT="http://localhost:2001"
      - AWS_TOPIC_PROCORE=${AWS_TOPIC_PROCORE}
      - AWS_TOPIC_INTACCT=${AWS_TOPIC_INTACCT}

volumes:
  procore-intacct-localstack-volume:
    driver: local
