AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Intacct Utilization HTTP API Gateway
      StageName: dev
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/lambda/api
      Handler: index.handler
      PackageType: Zip
      Runtime: nodejs14.x
      Events:
        Http:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /gateway
            Method: POST
Outputs:
  ApiGateway:
    Description: 'API Gateway endpoint URL for dev'
    Value: !Sub 'https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev'
